### ISSUE TITLE
Differences between the fast delta matrix algorithm and Dunkin's matrix algorithm

### ISSUE THREAD

**Issue by ChengSong233** [keurfonluu/disba#26]
Dear Keurfon Luu,

I test different methods of disba and compare it with the Geopsy using the example model that you give on Github, here are results:
![Rayleigh](https://user-images.githubusercontent.com/56331473/120171122-a6f78e00-c23c-11eb-9ce5-a2b087d81eea.png)
![Ellipticity](https://user-images.githubusercontent.com/56331473/120171160-b080f600-c23c-11eb-8a17-9b42bcc3b679.png)
So I am wondering if it is the inherent difference between these two algorithms?

**Comment by keurfonluu** [comment]
Hi @ChengSong233,

Thanks for reporting the issue. Geopsy is also using the Dunkin's matrix thus the same results. Nevertheless, according to Buchen and Ben-Hador's paper "Free-mode surface-wave computations" (which the fast-delta matrix algorithm is implemented from), these algorithms should yield comparable results (but they don't seem to have pushed the low frequencies). I am not sure whether my implementation is wrong but I don't think so since the dispersion curves are consistent at high frequencies.

To be safe and as I currently don't have much time to dedicate to my side projects, I switch back the default method to Dunkin's matrix.

Thanks again!

**Comment by ChengSong233** [comment]
Dear Keurfon Luu,

Thanks for your response, I am happy with your answer!

Cheers
Cheng
